# perception/ring_buffer.py
from __future__ import annotations

import logging
from dataclasses import dataclass, field
from typing import Dict, Deque, List, Optional, Tuple
from collections import deque
import numpy as np

from schemas import Frame

logger = logging.getLogger(__name__)


# ---------------------------------------------------------------------------
# DATA STRUCTURES
# ---------------------------------------------------------------------------

@dataclass
class BufferEntry:
    """
    Stores all temporal information for one track at one time step.

    This supports future phases:
      - FACE ROUTE:      face crops, face embeddings, quality scores
      - GAIT ROUTE:      pose keypoints, gait silhouettes
      - EVENTS:          posture, fallen detection, fight detection
      - EVIDENCE:        saving short clips for alerts

    Everything is optional except bbox + timestamp.
    """
    ts: float  # monotonic timestamp (Frame.ts)
    frame_index: int               # sequential index number from main_loop
    bbox: Tuple[float, float, float, float]

    # Optional future fields (safe to expand)
    crop: Optional[np.ndarray] = None             # person crop (BGR)
    appearance: Optional[np.ndarray] = None       # appearance embedding vector
    pose: Optional[np.ndarray] = None             # skeleton keypoints
    face_crop: Optional[np.ndarray] = None        # face region
    face_embedding: Optional[np.ndarray] = None
    face_quality: Optional[float] = None
    gait_vector: Optional[np.ndarray] = None
    event_feature: Optional[np.ndarray] = None


@dataclass
class RingBufferConfig:
    """
    Configure maximum time (seconds) kept per track and whether to store crops.

    max_seconds:
        How many seconds of history to keep per track.
        1–2 seconds recommended for tracking stability.
        3–5 seconds recommended for deep gait + face selection.

    store_crops:
        If False → do not store frame crops (saves memory).

    max_crops_per_track:
        If storing crops, enforce a hard limit for memory control.
    """
    max_seconds: float = 2.0
    store_crops: bool = True
    max_crops_per_track: int = 60   # safe limit (~2 seconds at 30 FPS)


# ---------------------------------------------------------------------------
# MAIN RING BUFFER
# ---------------------------------------------------------------------------

class RingBuffer:
    """
    Maintains per-track temporal history of the last N seconds.

    Key design goals:
      - Thread-safe for main_loop’s usage (single writer).
      - Efficient append + prune, O(1) operations.
      - Store only what future modules require (many optionals).
      - Clean extraction for gait/face/event pipelines.

    Structure:
        self.buffers = {
            track_id: deque([BufferEntry, BufferEntry, ...])
        }
    """

    def __init__(self, config: Optional[RingBufferConfig] = None):
        self.config = config or RingBufferConfig()
        self.buffers: Dict[int, Deque[BufferEntry]] = {}

    # ------------------------------------------------------------------ #
    # PUBLIC API
    # ------------------------------------------------------------------ #
    def add(
        self,
        track_id: int,
        ts: float,
        frame_index: int,
        bbox: Tuple[float, float, float, float],
        crop: Optional[np.ndarray] = None,
        appearance: Optional[np.ndarray] = None,
        pose: Optional[np.ndarray] = None,
        face_crop: Optional[np.ndarray] = None,
        face_embedding: Optional[np.ndarray] = None,
        face_quality: Optional[float] = None,
        gait_vector: Optional[np.ndarray] = None,
        event_feature: Optional[np.ndarray] = None,
    ) -> None:
        """
        Add a new entry to the ring buffer for a specific track ID.
        Automatically prunes old entries.

        Parameters
        ----------
        track_id : int
            Tracking ID from OCSortTracker.
        ts : float
            Monotonic timestamp from Frame.ts.
        frame_index : int
            Sequential frame index.
        bbox : tuple
            Person bounding box.
        crop / appearance / pose / face_crop / ... :
            Optional signals generated by perception_engine.
        """
        if track_id not in self.buffers:
            self.buffers[track_id] = deque()

        # Enforce crop memory rule
        if not self.config.store_crops:
            crop = None
            face_crop = None

        if self.config.store_crops and crop is not None:
            # Hard limit for memory control
            if len(self.buffers[track_id]) >= self.config.max_crops_per_track:
                self.buffers[track_id].popleft()

        entry = BufferEntry(
            ts=ts,
            frame_index=frame_index,
            bbox=bbox,
            crop=crop,
            appearance=appearance,
            pose=pose,
            face_crop=face_crop,
            face_embedding=face_embedding,
            face_quality=face_quality,
            gait_vector=gait_vector,
            event_feature=event_feature,
        )

        self.buffers[track_id].append(entry)

        # Prune based on timestamp
        self._prune(track_id, ts)

    def get(self, track_id: int) -> List[BufferEntry]:
        """
        Return the current list of buffer entries for this track.
        Latest element is the most recent one.
        """
        if track_id not in self.buffers:
            return []
        return list(self.buffers[track_id])

    def get_latest(self, track_id: int) -> Optional[BufferEntry]:
        """
        Return the last entry (most recent) for this track.
        """
        if track_id not in self.buffers or len(self.buffers[track_id]) == 0:
            return None
        return self.buffers[track_id][-1]

    def remove_track(self, track_id: int) -> None:
        """
        Remove a track's entire buffer (optional cleanup when tracker deactivates).
        """
        if track_id in self.buffers:
            del self.buffers[track_id]

    def cleanup_dead_tracks(self, active_track_ids: List[int]) -> None:
        """
        Remove buffers for tracks no longer active in the tracker.
        """
        for tid in list(self.buffers.keys()):
            if tid not in active_track_ids:
                del self.buffers[tid]

    # ------------------------------------------------------------------ #
    # INTERNAL HELPERS
    # ------------------------------------------------------------------ #
    def _prune(self, track_id: int, current_ts: float) -> None:
        """
        Remove entries older than (current_ts - max_seconds).
        """
        max_age = self.config.max_seconds
        buf = self.buffers.get(track_id)
        if buf is None:
            return

        # Pop from left while too old
        while len(buf) > 0 and (current_ts - buf[0].ts) > max_age:
            buf.popleft()

    # ------------------------------------------------------------------ #
    # ADVANCED ACCESSORS (for future phases)
    # ------------------------------------------------------------------ #

    def get_last_n_entries(self, track_id: int, n: int) -> List[BufferEntry]:
        """
        Return last n entries (for short sequence analysis).
        """
        if track_id not in self.buffers:
            return []
        buf = self.buffers[track_id]
        return list(buf)[-n:]

    def get_time_window(
        self,
        track_id: int,
        window_sec: float,
        current_ts: float,
    ) -> List[BufferEntry]:
        """
        Return all entries within the last window_sec seconds.
        Useful for:
            - selecting best face crop
            - gait sequence extraction
            - event classification (fight, fallen)
        """
        if track_id not in self.buffers:
            return []

        buf = self.buffers[track_id]
        min_ts = current_ts - window_sec
        return [e for e in buf if e.ts >= min_ts]
