"""
gait/gait_engine.py
Integrates GaitExtractor and GaitGallery to process Tracklets with pose data
and produce identity recognition decisions based on gait.
"""
from __future__ import annotations
import logging
from typing import List, Optional
import numpy as np
from schemas import Frame, Tracklet
from schemas.id_signals import IdSignal
from schemas.identity_decision import IdentityDecision
from gait.config import GaitConfig, default_gait_config
from gait.gait_extractor import GaitExtractor
from gait.gait_gallery import GaitGallery

logger = logging.getLogger(__name__)

class GaitEngine:
    def __init__(self):
        """
        Initializes the GaitEngine.
        
        How it works:
        1. Loads the default configuration.
        2. Instantiates the `GaitExtractor` (which holds the neural network model 
           for converting pose sequences into embeddings).
        3. Instantiates the `GaitGallery` (which holds the database of known 
           identities and performs vector similarity searches).
        """
        self.config = default_gait_config()
        self.extractor = GaitExtractor(self.config)
        self.gallery = GaitGallery(self.config)
        logger.info("GaitEngine initialized")

    def update_signals(self, frame: Frame, tracks: List[Tracklet]) -> List[IdSignal]:
        """
        Processes active tracklets to generate identification signals.
        
        How it works:
        1. Iterates through all current `Tracklet` objects provided by the perception engine.
        2. Checks if the tracklet contains `gait_sequence_data` (a buffer of recent poses).
        3. **Extraction**: Calls `self.extractor` to convert the sequence of poses into 
           a mathematical vector (embedding) and a quality score.
        4. **Matching**: If a valid embedding is generated, calls `self.gallery.search` 
           to compare it against known identities.
        5. **Signal Creation**: Wraps the result (matched identity ID, confidence, etc.) 
           into an `IdSignal` object.
           
        Args:
            frame: The current video frame.
            tracks: List of tracked objects (people) in the scene.
            
        Returns:
            List[IdSignal]: A list of raw identification results from this frame.
        """
        signals = []
        for track in tracks:
            if not track.gait_sequence_data:
                continue
                
            # Extract embedding from the sequence of poses
            embedding, quality = self.extractor.extract_gait_embedding_and_quality(track.gait_sequence_data)
            
            # Update quality metric on the tracklet for UI visualization
            track.gait_quality = quality
            
            if embedding is not None:
                # Search in gallery for the closest match
                match_id, confidence = self.gallery.search(embedding)
                
                # Create an identity signal
                # Contains: track_id, identity_id (name or None), confidence (0-1), method="gait"
                signal = IdSignal(
                    track_id=track.track_id,
                    identity_id=match_id,  # Will be None if unknown or below threshold
                    confidence=confidence if confidence else 0.0,
                    method="gait"
                )
                signals.append(signal)
            
        return signals

    def decide(self, signals: List[IdSignal]) -> List[IdentityDecision]:
        """
        Converts raw IdSignals into final IdentityDecisions.
        
        How it works:
        1. Takes the raw signals generated by `update_signals`.
        2. Enriches the decision by querying the gallery for metadata (like the 
           category of the person, e.g., "employee", "visitor").
        3. Constructs a standardized `IdentityDecision` object that can be 
           consumed by the UI Overlay or Alert Engine.
           
        Args:
            signals: List of raw signals from the current frame.
            
        Returns:
            List[IdentityDecision]: Final decisions ready for display/logging.
        """
        decisions = []
        for signal in signals:
            identity_id = None
            category = "unknown"
            confidence = 0.0
            
            # If the signal found a valid match (i.e., not None)
            if signal.identity_id:
                identity_id = signal.identity_id
                confidence = signal.confidence
                
                # Retrieve category (e.g., 'staff', 'vip') from gallery metadata
                category = self.gallery.get_category(identity_id)
            
            # Create final decision object
            decision = IdentityDecision(
                track_id=signal.track_id,
                identity_id=identity_id,
                category=category, 
                confidence=confidence,
                reason=f"Matched by {signal.method}"
            )
            decisions.append(decision)
            
        return decisions