# schemas/tracklet.py
from dataclasses import dataclass, field
from typing import List, Tuple, Optional
import numpy as np

@dataclass
class Tracklet:
    """
    Represents a single moving person/object tracked over time.

    Changes for Silhouette-based Gait Recognition:
    - gait_sequence_data now holds binary masks (silhouettes).
    """
    track_id: int
    camera_id: str
    last_frame_id: int
    last_box: Tuple[float, float, float, float]
    confidence: float

    age_frames: int = 0
    lost_frames: int = 0
    history_boxes: List[Tuple[float, float, float, float]] = field(
        default_factory=list
    )

    """
    GAIT RECOGNITION DATA (SILHOUETTE VERSION)
    
    This field contains the sequence of binary silhouettes (masks) for this person.
    
    Format: List of np.ndarray.
    Each array shape: (64, 64) -> Normalized size for GaitSet model.
    Dtype: uint8 (0 = background, 255 = person).
    """
    gait_sequence_data: List[np.ndarray] = field(default_factory=list)

    # The numeric embedding vector (e.g., 256-dim) extracted from the silhouette sequence.
    # Generated by GaitExtractor.
    gait_embedding: Optional[np.ndarray] = None
    
    # Quality score (0.0 - 1.0) of the gait sequence (based on silhouette integrity).
    gait_quality: float = 0.0
    
    # ID of the person recognized by the GaitEngine (e.g., "JohnDoe").
    gait_identity_id: Optional[str] = None

    # Confidence of the recognition (0.0 - 1.0).
    gait_confidence: Optional[float] = None